name: flutter_music_render
description: A Flutter package for rendering musical notation and providing keyboard input.
version: 0.1.0
homepage: https://github.com/musescore/musescore

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Bravura
      fonts:
        - asset: assets/fonts/Bravura.otf